### ISSUE TITLE
Roadmap / tracker

### ISSUE THREAD

**Issue by tervay** [tervay/recalc#1226]
List is in no particular order.

- [ ] Differentiate between supply & stator currents
- [ ] Allow user to choose between supply & stator current limits
- [ ] Differential eq model for all calcs
- [ ] Overhaul UI for ratio finder
- [ ] New algorithm for ratio finder -- tree searching
- [ ] Overhaul UI to use tailwind + shadcn
- [ ] Rewrite IO fields to be less complex/nested
- [ ] Add component tests
- [ ] Add UI tests for pneumatics
- [ ] Add UI tests for linear mech
- [ ] Add UI tests for intake
- [ ] Add UI tests for ratio calculator
- [ ] Add UI tests for ratio finder
- [ ] Add UI tests for motors page
- [ ] Fix About Recalc icon size
- [ ] Add bearing finder
- [ ] Add "older games" cheat sheet links page
- [ ] Add flywheel [recovery time, windup time] vs MOI chart
- [ ] Add linear [time to goal, total power consumed] vs ratio chart
- [ ] Add kE to motor playground
- [ ]  X axis “% of free speed” on motor playground
